#!/bin/bash
# mvn_build_compile.sh -- Run Maven compile phase.
# Uses the CI settings.xml generated by setup_maven_settings.sh.
# Cache restore/save for ~/.m2/repository is handled by the calling command YAML.
#
# Parameters (via environment):
#   PARAM_MAVEN_ARGS  Extra Maven arguments (default: none)
set -euo pipefail

MAVEN_ARGS="${PARAM_MAVEN_ARGS:-}"

echo "Running Maven compile..."
# shellcheck disable=SC2086
mvn -s /tmp/circleci/mvn-settings.xml --no-transfer-progress \
  compile ${MAVEN_ARGS}
echo "Compile complete"
