#!/bin/bash
# mvn_verify.sh -- Run Maven verify phase (compile, test, package).
# Uses the CI settings.xml generated by setup_maven_settings.sh.
# JaCoCo and test result collection are handled by the calling command YAML.
#
# Parameters (via environment):
#   PARAM_MAVEN_ARGS  Extra Maven arguments (default: none)
set -euo pipefail

MAVEN_ARGS="${PARAM_MAVEN_ARGS:-}"

echo "Running Maven verify..."
# shellcheck disable=SC2086
mvn -s /tmp/circleci/mvn-settings.xml --no-transfer-progress \
  verify ${MAVEN_ARGS}
echo "Verify complete"
