#!/bin/bash
# mvn_checkstyle.sh -- Run Maven Checkstyle validation.
# Uses the CI settings.xml generated by setup_maven_settings.sh.
# Requires a checkstyle configuration in the project (typically checkstyle.xml).
#
# Parameters (via environment):
#   PARAM_MAVEN_ARGS  Extra Maven arguments (default: none)
set -euo pipefail

MAVEN_ARGS="${PARAM_MAVEN_ARGS:-}"

echo "Running Maven Checkstyle..."
# shellcheck disable=SC2086
mvn -s /tmp/circleci/mvn-settings.xml --no-transfer-progress \
  checkstyle:check ${MAVEN_ARGS}
echo "Checkstyle passed"
